/*
* This header is generated by classdump-dyld 0.2
* on Friday, January 3, 2014 at 2:16:19 AM Eastern European Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/BiometricKit.framework/BiometricKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol BiometricKitDelegate <NSObject>
@optional
-(void)statusMessage:(unsigned)arg1;
-(void)enrollResult:(id)arg1;
-(void)matchResult:(id)arg1;
-(void)homeButtonPressed;
-(void)enrollProgress:(id)arg1;
-(void)matchResult:(id)arg1 withDetails:(id)arg2;
@end

