/*
* This header is generated by classdump-dyld 0.2
* on Friday, January 3, 2014 at 2:16:19 AM Eastern European Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/BiometricKit.framework/BiometricKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol BiometricKitDelegate;
@class NSXPCConnection;

@interface BiometricKitXPCClient : NSObject {

	NSXPCConnection* _connection;
	<BiometricKitDelegate>* _delegate;
	/*^block*/ id _interruptionHandler;

}

@property (assign,nonatomic) <BiometricKitDelegate> * delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) id interruptionHandler;                           //@synthesize interruptionHandler=_interruptionHandler - In the implementation block
-(void)statusMessage:(unsigned)arg1 ;
-(/*^block*/ id)interruptionHandler;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(id)init;
-(id)delegate;
-(void)cancel;
-(void)connect;
-(void)setInterruptionHandler:(/*^block*/ id)arg1 ;
-(void)enrollResult:(id)arg1 ;
-(void)matchResult:(id)arg1 ;
-(void)homeButtonPressed;
-(void)suspendWork:(bool)arg1 ;
-(int)enroll:(int)arg1 withAuthToken:(id)arg2 ;
-(int)match:(id)arg1 withOptions:(id)arg2 ;
-(int)matchIdentities:(id)arg1 ;
-(id)getIdentityFromUUID:(id)arg1 ;
-(int)resetEngine;
-(int)enrollContinue;
-(id)pullAlignmentData;
-(id)pullMatchTopologyData;
-(id)getNodeTopologyForIdentity:(id)arg1 ;
-(int)preventAutonomousMatchingMode:(bool)arg1 ;
-(long long)getProvisioningState;
-(int)registerDSID:(unsigned long long)arg1 withAuthToken:(id)arg2 ;
-(int)registerStoreToken:(id)arg1 ;
-(int)getCountersignedStoreToken:(id*)arg1 ;
-(long long)getCalBlobVersion;
-(long long)getSensorCalibrationStatus;
-(long long)getCalibrationDataState;
-(id)pullCaptureBuffer;
-(id)pullDebugImageData:(bool)arg1 imageWidth:(unsigned*)arg2 imageHeight:(unsigned*)arg3 ;
-(int)provisionSensor;
-(int)unpairSensor;
-(int)lockSensor;
-(void)setDebugImages:(bool)arg1 ;
-(id)getSerialisedTemplateForIdentity:(id)arg1 ;
-(void)registerDelegate:(bool)arg1 ;
-(int)match:(id)arg1 ;
-(id)identities:(id)arg1 ;
-(long long)getMaxIdentityCount:(int)arg1 ;
-(int)removeIdentity:(id)arg1 ;
-(int)updateIdentity:(id)arg1 ;
@end

